### ISSUE TITLE
Update package for use in new versions of Python

### ISSUE THREAD

**Issue by mojikarimi** [petebachant/Nortek-Python#6]
# Update package

This version of Nortek-Python does not support Python version 3 well and some of the libraries and modules used in it are obsolete and those libraries are no longer available.

### For example:

- UserDict

Or even to import, according to the example(`from nortek.controls import PdControl`), we encounter the following error, which does not allow working with this package at first.

```python

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\nortek\controls.py", line 12, in <module>
    import win32com.client as _wc
  File "C:\Python312\Lib\site-packages\win32com\__init__.py", line 8, in <module>
    import pythoncom
  File "C:\Python312\Lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Python312\Lib\pywintypes.py", line 130, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python312\Lib\pywintypes.py", line 101, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes312.dll)

```

**Hint:** This has also been done for lower versions of Python and we have encountered the same error.

**Comment by petebachant** [comment]
What does your environment look like? Have you installed pywin32 (`pip install pywin32`)?

**Comment by mojikarimi** [comment]
Yes, it is installed.
I even tested several times in different virtual environments to make sure, but it still doesn't have the `pywintypes` module.
I even tried to install this module via pip install `pywintypes` but this module does not exist and it gave me the following error:

```cmd

ERROR: Could not find a version that satisfies the requirement pywintypes (from versions: none)
ERROR: No matching distribution found for pywintypes

```

Apparently, this module is one of the requirements of the `pywin32` module, but it does not exist.
Even by searching on different sites, I found the files and added them manually, but I still had problems.

In my opinion, this code should be rewritten and optimized with `Python3` and `Python3` modules.
But I can't identify the structure of the code, because I can't run the code, so I can't understand its logic and function.
If you can tell the logic of the codes or give the algorithm of **`vno`** files so that I can read these types of files, I will be grateful.
